/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ponei;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author s.lucas
 */
public class menuNums extends javax.swing.JFrame {

    /**
     * Creates new form menuNums
     */
    public menuNums() {
        initComponents();
        txtNumLista.setText("sua lista esta vazia");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInforme = new javax.swing.JLabel();
        btNumSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNumLista = new javax.swing.JTextArea();
        lbPesquisar = new javax.swing.JLabel();
        btNumBuscar = new javax.swing.JButton();
        btNumExcluir = new javax.swing.JButton();
        btNumAlterar = new javax.swing.JButton();
        btVerQuant = new javax.swing.JButton();
        btGerarTabuada3 = new javax.swing.JButton();
        btLimparLista = new javax.swing.JButton();
        txtNumSalvar = new javax.swing.JTextField();
        txtNumPesq = new javax.swing.JTextField();
        btVerificar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbInforme.setText("informe um numero impar");

        btNumSalvar.setText("salvar");
        btNumSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumSalvarActionPerformed(evt);
            }
        });

        txtNumLista.setEditable(false);
        txtNumLista.setColumns(20);
        txtNumLista.setRows(5);
        txtNumLista.setTabSize(7);
        jScrollPane2.setViewportView(txtNumLista);

        lbPesquisar.setText("pesquisar");

        btNumBuscar.setText("buscar");
        btNumBuscar.setEnabled(false);
        btNumBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumBuscarActionPerformed(evt);
            }
        });

        btNumExcluir.setText("excluir");
        btNumExcluir.setEnabled(false);
        btNumExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumExcluirActionPerformed(evt);
            }
        });

        btNumAlterar.setText("alterar");
        btNumAlterar.setEnabled(false);
        btNumAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNumAlterarActionPerformed(evt);
            }
        });

        btVerQuant.setText("ver quantidade");
        btVerQuant.setEnabled(false);
        btVerQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerQuantActionPerformed(evt);
            }
        });

        btGerarTabuada3.setText("gerar tabuada do 3 elemento");
        btGerarTabuada3.setEnabled(false);
        btGerarTabuada3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarTabuada3ActionPerformed(evt);
            }
        });

        btLimparLista.setText("limpar lista");
        btLimparLista.setEnabled(false);
        btLimparLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparListaActionPerformed(evt);
            }
        });

        txtNumSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumSalvarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumSalvarKeyReleased(evt);
            }
        });

        txtNumPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumPesqKeyReleased(evt);
            }
        });

        btVerificar1.setText("verificar se 1° numero e positivo ou negativo");
        btVerificar1.setEnabled(false);
        btVerificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerificar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btVerQuant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLimparLista))
                            .addComponent(lbInforme)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNumSalvar)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btNumSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btNumBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(lbPesquisar))
                                            .addComponent(btNumExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btNumAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(txtNumPesq)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btVerificar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btGerarTabuada3)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbInforme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNumSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPesquisar)
                        .addGap(11, 11, 11)
                        .addComponent(txtNumPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNumBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btNumExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btNumAlterar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVerQuant)
                    .addComponent(btLimparLista))
                .addGap(18, 18, 18)
                .addComponent(btGerarTabuada3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVerificar1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    logicaNums api = new logicaNums();

    private void estadoBotoes(boolean estado) {
        btNumExcluir.setEnabled(estado);
        btNumAlterar.setEnabled(estado);
        btNumBuscar.setEnabled(estado);
        btVerQuant.setEnabled(estado);
        btLimparLista.setEnabled(estado);
        btGerarTabuada3.setEnabled(estado);
        btVerificar1.setEnabled(estado);
        txtNumPesq.setEnabled(estado);
    }

    private void salvar() {
        if (txtNumSalvar.getText().isEmpty()){
            return;
        }
        int numsalvar = Integer.parseInt(txtNumSalvar.getText());
        boolean status = api.salvar(numsalvar);
        if (status) {
            estadoBotoes(true);
            txtNumSalvar.setText(null);
            txtNumLista.setText(api.listar());
        }
    }

    private void btNumSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumSalvarActionPerformed
        salvar();
        //estadoBotoes(true);
    }//GEN-LAST:event_btNumSalvarActionPerformed

    private void btLimparListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparListaActionPerformed
        txtNumLista.setText(api.limpar());
        estadoBotoes(false);
    }//GEN-LAST:event_btLimparListaActionPerformed

    private void btNumBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumBuscarActionPerformed
        int numpesq = Integer.parseInt(txtNumPesq.getText());
        api.buscar(numpesq);
    }//GEN-LAST:event_btNumBuscarActionPerformed

    private void txtNumSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSalvarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar();
        }
    }//GEN-LAST:event_txtNumSalvarKeyPressed

    private void btVerQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerQuantActionPerformed
        api.quantidade();
    }//GEN-LAST:event_btVerQuantActionPerformed

    private void btNumExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumExcluirActionPerformed
        boolean status = api.remover(Integer.parseInt(txtNumPesq.getText()));
        if (status) {
            String listanova = api.listar();
            txtNumLista.setText(listanova);
            if (listanova == "sua lista esta vazia") {
                estadoBotoes(false);
            }
        }
    }//GEN-LAST:event_btNumExcluirActionPerformed

    private void btNumAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNumAlterarActionPerformed
        boolean status = api.editar(Integer.parseInt(txtNumPesq.getText()));
        if (status) {
            txtNumLista.setText(api.listar());
        }
    }//GEN-LAST:event_btNumAlterarActionPerformed

    private void txtNumSalvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumSalvarKeyReleased
        txtNumSalvar.setText(txtNumSalvar.getText().replaceAll("[^0-9\\-]", ""));
    }//GEN-LAST:event_txtNumSalvarKeyReleased

    private void txtNumPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPesqKeyReleased
        txtNumPesq.setText(txtNumPesq.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_txtNumPesqKeyReleased

    private void btGerarTabuada3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarTabuada3ActionPerformed
        api.gerartabuada3();
    }//GEN-LAST:event_btGerarTabuada3ActionPerformed

    private void btVerificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerificar1ActionPerformed
        api.verificar1();
    }//GEN-LAST:event_btVerificar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuNums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuNums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuNums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuNums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuNums().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarTabuada3;
    private javax.swing.JButton btLimparLista;
    private javax.swing.JButton btNumAlterar;
    private javax.swing.JButton btNumBuscar;
    private javax.swing.JButton btNumExcluir;
    private javax.swing.JButton btNumSalvar;
    private javax.swing.JButton btVerQuant;
    private javax.swing.JButton btVerificar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbInforme;
    private javax.swing.JLabel lbPesquisar;
    private javax.swing.JTextArea txtNumLista;
    private javax.swing.JTextField txtNumPesq;
    private javax.swing.JTextField txtNumSalvar;
    // End of variables declaration//GEN-END:variables
}
